import type { Config } from "tailwindcss";

/**
 * Design system: "Atelier Warmth" — Calm Luxury.
 * Tokens copied verbatim from the Stitch blueprint (DESIGN.md) so the
 * Next.js build renders pixel-identical to the static design.
 */
const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#5c6651",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#d3c4b5",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#161e0e",
        "outline-variant": "#d3c3bb",
        "surface-tint": "#755845",
        "surface-dim": "#dcd9d9",
        "surface-container-high": "#eae7e7",
        "primary-fixed": "#ffdcc6",
        "on-primary-container": "#e7c1a9",
        "tertiary-container": "#5d5246",
        "inverse-on-surface": "#f3f0f0",
        "surface-container-lowest": "#ffffff",
        outline: "#81756d",
        tertiary: "#453b30",
        "primary-container": "#6a4e3b",
        "on-tertiary-container": "#d5c6b7",
        secondary: "#58624d",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#4f453a",
        background: "#fbf9f8",
        "on-surface-variant": "#4f453e",
        "on-secondary-fixed-variant": "#404a37",
        "on-background": "#1b1c1c",
        "surface-variant": "#e4e2e1",
        "surface-container-low": "#f6f3f2",
        "on-primary-fixed-variant": "#5b412f",
        "on-error": "#ffffff",
        "surface-bright": "#fbf9f8",
        "on-primary": "#ffffff",
        "surface-container": "#f0eded",
        "secondary-container": "#d9e3ca",
        "inverse-surface": "#303030",
        "on-secondary": "#ffffff",
        primary: "#513726",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#221a11",
        "tertiary-fixed": "#f0e0d1",
        "on-primary-fixed": "#2b1708",
        "primary-fixed-dim": "#e5bfa7",
        "inverse-primary": "#e5bfa7",
        "secondary-fixed-dim": "#c0cab1",
        "secondary-fixed": "#dce6cc",
        "on-surface": "#1b1c1c",
        "surface-container-highest": "#e4e2e1",
        surface: "#fbf9f8",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "16px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        unit: "8px",
        "stack-md": "32px",
        "margin-mobile": "20px",
        gutter: "24px",
        "stack-lg": "80px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["var(--font-dm-sans)", "DM Sans", "sans-serif"],
        serif: ["var(--font-cormorant)", "Cormorant Garamond", "serif"],
        "label-sm": ["var(--font-dm-sans)", "DM Sans"],
        "body-lg": ["var(--font-dm-sans)", "DM Sans"],
        "display-hero-mobile": ["var(--font-cormorant)", "Cormorant Garamond", "serif"],
        "body-md": ["var(--font-dm-sans)", "DM Sans"],
        "headline-section-mobile": ["var(--font-cormorant)", "Cormorant Garamond", "serif"],
        "label-xs": ["var(--font-dm-sans)", "DM Sans"],
        "display-hero": ["var(--font-cormorant)", "Cormorant Garamond", "serif"],
        "headline-section": ["var(--font-cormorant)", "Cormorant Garamond", "serif"],
        subheading: ["var(--font-cormorant)", "Cormorant Garamond", "serif"],
      },
      fontSize: {
        "label-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-hero-mobile": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-section-mobile": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "label-xs": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-hero": ["72px", { lineHeight: "84px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-section": ["40px", { lineHeight: "52px", letterSpacing: "-0.01em", fontWeight: "500" }],
        subheading: ["22px", { lineHeight: "32px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
