"use client";

import React, { useId } from "react";
import { AlertCircle, Lock } from "lucide-react";

interface SlugFieldProps {
  value: string;
  onChange: (value: string) => void;
  locked?: boolean;
  isPublished?: boolean;
  autoGenerated?: boolean;
  error?: string;
  disabled?: boolean;
}

/**
 * Slug input with:
 * - Auto-generation from name (controlled externally via value prop)
 * - Lock state after publish (with warning icon)
 * - Visible lock icon and tooltip when slug is frozen
 */
export function SlugField({
  value,
  onChange,
  locked = false,
  isPublished = false,
  error,
  disabled = false,
}: SlugFieldProps) {
  const id = useId();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    // Sanitize: lowercase, replace spaces with hyphens, strip invalid chars
    const sanitized = e.target.value
      .toLowerCase()
      .replace(/\s+/g, "-")
      .replace(/[^a-z0-9-]/g, "")
      .replace(/-{2,}/g, "-"); // collapse multiple hyphens
    onChange(sanitized);
  };

  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between">
        <label
          htmlFor={id}
          className="text-xs font-medium text-secondary uppercase tracking-wider"
        >
          Slug
        </label>
        {locked && (
          <span className="flex items-center gap-1 text-[10px] text-amber-400 font-medium">
            <Lock className="h-2.5 w-2.5" />
            Locked after publish
          </span>
        )}
      </div>

      <div className="relative">
        <span className="
          absolute left-3 top-1/2 -translate-y-1/2
          text-xs text-secondary select-none pointer-events-none
        ">
          /
        </span>
        <input
          id={id}
          type="text"
          value={value}
          onChange={handleChange}
          disabled={locked || disabled}
          className={`
            w-full h-8 pl-6 pr-3 text-xs font-mono
            bg-panel border rounded-md
            text-primary placeholder:text-secondary
            focus:outline-none focus:ring-1 focus:ring-gold/50 focus:border-gold/50
            transition-all duration-150
            ${locked ? "opacity-60 cursor-not-allowed border-muted" : "border-muted hover:border-gold/30"}
            ${error ? "border-red-500/50 focus:ring-red-500/30" : ""}
          `}
          placeholder="my-taxonomy-slug"
          aria-label="URL slug"
          aria-describedby={error ? `${id}-error` : undefined}
          spellCheck={false}
          autoComplete="off"
        />
        {locked && (
          <Lock className="absolute right-3 top-1/2 -translate-y-1/2 h-3 w-3 text-secondary" />
        )}
      </div>

      {isPublished && !locked && (
        <p className="flex items-center gap-1.5 text-[10px] text-amber-400">
          <AlertCircle className="h-2.5 w-2.5 shrink-0" />
          This node has been published. Changing the slug may break existing links.
          Ensure redirects are configured.
        </p>
      )}

      {error && (
        <p id={`${id}-error`} className="text-[10px] text-red-400">
          {error}
        </p>
      )}

      {!error && !locked && (
        <p className="text-[10px] text-secondary">
          Auto-generated from name. Edit until first publish.
        </p>
      )}
    </div>
  );
}

/**
 * Utility: generate a URL-safe slug from a display name
 */
export function generateSlug(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_]+/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "");
}
